### ISSUE TITLE
add a timer to the credits 

### ISSUE THREAD

**Issue by booshican** [Hypatech/ULTRAKILL-Speedrunner-Issues#43] opened 2024-05-23 20:03 UTC
very minor additional but the credits having a timer could allow for one of the two RTA speedruns in ultrakill, all style bonuses, to be in IGT.

**Comment by glass-source** [comment] 2024-05-23 23:55
Adding on to this, would be nice if we could have a timer in sandbox. This would make timing kills or certain combos in there easier, as there's no way of timing those unless you do them on a level with a timer. Not really necessary but its good practice to have features like this.

**Comment by kekson1a** [comment] 2024-05-27 13:44
is this a duplicate of #24 ?

**Comment by booshican** [comment] 2024-05-27 15:47
it looks like it is. imma close it due to being a duplicate

**Closed as completed** 2024-05-27 15:47 UTC
